test:debian6:
    image: debian:6    
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - chmod +x inst/deb.sh
        - inst/deb.sh
        - custom_motd

test:debian7:
    image: debian:7
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - chmod +x inst/deb.sh
        - inst/deb.sh
        - custom_motd
